[misc]
disable = ["mas", "gem", "ruby_gems", "pnpm", "pip3", "yarn", "asdf"]

[git]
arguments = "--rebase --autostash"
repos = ["~/.config/nvim", "~/.fzf/fzf-git.sh"]

[commands]
"lazy.nvim plugins" = 'nvim --headless "+Lazy! sync" +qa'
"Brew upgrade HEAD" = "HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade --fetch-HEAD"
# "Wezterm nightly" = "HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest"
"Claude Code update" = "claude update"
"gh extensions upgrade" = "gh extension upgrade --all"
"tuicr upgrade" = "cargo install tuicr"
